--cognos专用用户
drop user cognos;
create user cognos identified by cognos default tablespace COGNOS_DATA;
grant "CONNECT" to cognos;
grant "RESOURCE" to cognos;
grant unlimited tablespace to cognos;
grant select on sxdxsj.D_ACCEPT_DONATION to cognos;
grant select on sxdxsj.D_AGE_INFO to cognos;
grant select on sxdxsj.D_BANK_STATUS_INFO to cognos;
grant select on sxdxsj.D_BIRTHDATE_MONTH to cognos;
grant select on sxdxsj.D_BRANCH_DELIVERY to cognos;
grant select on sxdxsj.D_BRANCH_INFO to cognos;
grant select on sxdxsj.D_COMPANY_DELIVERY to cognos;
grant select on sxdxsj.D_CUSTOMER_LEVEL to cognos;
grant select on sxdxsj.D_DIAL_STATUS_INFO to cognos;
grant select on sxdxsj.D_DIAL_TIME_LENGTH to cognos;
grant select on sxdxsj.D_DIAL_TIMES to cognos;
grant select on sxdxsj.D_FROM_REVIST_TIME to cognos;
grant select on sxdxsj.D_GENDER to cognos;
grant select on sxdxsj.D_HAS_CTELE to cognos;
grant select on sxdxsj.D_HAS_FTELE to cognos;
grant select on sxdxsj.D_HAS_MOBILE to cognos;
grant select on sxdxsj.D_HAS_RECTELE to cognos;
grant select on sxdxsj.D_MONTH_AMOUNT to cognos;
grant select on sxdxsj.D_OPERATION_STATUS_INFO to cognos;
grant select on sxdxsj.D_ORPHAN_STATUS to cognos;
grant select on sxdxsj.D_PAY_BY_BANK to cognos;
grant select on sxdxsj.D_PAY_BY_POS to cognos;
grant select on sxdxsj.D_POLICY_STATUS to cognos;
grant select on sxdxsj.D_SALE_PERIOD to cognos;
grant select on sxdxsj.D_SALE_STATUS_INFO to cognos;
grant select on sxdxsj.D_SOURCE_FROM_INFO to cognos;
grant select on sxdxsj.D_ZONE_TYPE to cognos;
grant select on sxdxsj.customer to cognos;